version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always  
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: keni
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: iluvcoffee
